#linear regression practical implementation

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [7]:
from sklearn.datasets import fetch_openml
boston = fetch_openml(name = 'boston', version = 1, as_frame = True, parser = 'pandas')

In [8]:
boston

{'data':         CRIM    ZN  INDUS CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
 0    0.00632  18.0   2.31    0  0.538  ...    1  296.0     15.3  396.90   4.98
 1    0.02731   0.0   7.07    0  0.469  ...    2  242.0     17.8  396.90   9.14
 2    0.02729   0.0   7.07    0  0.469  ...    2  242.0     17.8  392.83   4.03
 3    0.03237   0.0   2.18    0  0.458  ...    3  222.0     18.7  394.63   2.94
 4    0.06905   0.0   2.18    0  0.458  ...    3  222.0     18.7  396.90   5.33
 ..       ...   ...    ...  ...    ...  ...  ...    ...      ...     ...    ...
 501  0.06263   0.0  11.93    0  0.573  ...    1  273.0     21.0  391.99   9.67
 502  0.04527   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   9.08
 503  0.06076   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   5.64
 504  0.10959   0.0  11.93    0  0.573  ...    1  273.0     21.0  393.45   6.48
 505  0.04741   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   7.88

 [506 rows x 13 columns],
 'target': 0      24.0
 1      21.6
 2      34.7
 3      33.4
 4      36.2
        ...
 501    22.4
 502    20.6
 503    23.9
 504    22.0
 505    11.9
 Name: MEDV, Length: 506, dtype: float64,
 'frame':         CRIM    ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B LSTAT  MEDV
 0    0.00632  18.0   2.31    0  0.538  ...  296.0     15.3  396.90  4.98  24.0
 1    0.02731   0.0   7.07    0  0.469  ...  242.0     17.8  396.90  9.14  21.6
 2    0.02729   0.0   7.07    0  0.469  ...  242.0     17.8  392.83  4.03  34.7
 3    0.03237   0.0   2.18    0  0.458  ...  222.0     18.7  394.63  2.94  33.4
 4    0.06905   0.0   2.18    0  0.458  ...  222.0     18.7  396.90  5.33  36.2
 ..       ...   ...    ...  ...    ...  ...    ...      ...     ...   ...   ...
 501  0.06263   0.0  11.93    0  0.573  ...  273.0     21.0  391.99  9.67  22.4
 502  0.04527   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  9.08  20.6
 503  0.06076   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  5.64  23.9
 504  0.10959   0.0  11.93    0  0.573  ...  273.0     21.0  393.45  6.48  22.0
 505  0.04741   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  7.88  11.9

 [506 rows x 14 columns],
 'categories': None,
 'feature_names': ['CRIM',
  'ZN',
  'INDUS',
  'CHAS',
  'NOX',
  'RM',
  'AGE',
  'DIS',
  'RAD',
  'TAX',
  'PTRATIO',
  'B',
  'LSTAT'],
 'target_names': ['MEDV'],
 'DESCR': "**Author**:   \n**Source**: Unknown - Date unknown  \n**Please cite**:   \n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\nVariables in order:\nCRIM     per capita crime rate by town\nZN       proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS    proportion of non-retail business acres per town\nCHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\nNOX      nitric oxides concentration (parts per 10 million)\nRM       average number of rooms per dwelling\nAGE      proportion of owner-occupied units built prior to 1940\nDIS      weighted distances to five Boston employment centres\nRAD      index of accessibility to radial highways\nTAX      full-value property-tax rate per $10,000\nPTRATIO  pupil-teacher ratio by town\nB        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT    % lower status of the population\nMEDV     Median value of owner-occupied homes in $1000's\n\n\nInformation about the dataset\nCLASSTYPE: numeric\nCLASSINDEX: last\n\nDownloaded from openml.org.",
 'details': {'id': '531',
  'name': 'boston',
  'version': '1',
  'description_version': '1',
  'format': 'ARFF',
  'creator': ['D. and Rubinfeld', "D.L. 'Hedonic"],
  'collection_date': '1978',
  'upload_date': '2014-09-29T00:08:07',
  'language': 'English',
  'licence': 'Public',
  'url': 'https://openml.org/data/v1/download/52643/boston.arff',
  'parquet_url': 'https://data.openml.org/datasets/0000/0531/dataset_531.pq',
  'file_id': '52643',
  'default_target_attribute': 'MEDV',
  'tag': ['Data Science',
   'Housing Economics',
   'Kaggle',
   'OpenML-Reg19',
   'study_130',
   'Urban Studies'],
  'visibility': 'public',
  'status': 'active',
  'processing_date': '2020-11-20 20:16:37',
  'md5_checksum': 'cdd361fb886627eaa80c92f90d0610cc'},
 'url': 'https://www.openml.org/d/531'}

In [9]:
df = boston.frame

In [10]:
df.head()

      CRIM    ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B LSTAT  MEDV
0  0.00632  18.0   2.31    0  0.538  ...  296.0     15.3  396.90  4.98  24.0
1  0.02731   0.0   7.07    0  0.469  ...  242.0     17.8  396.90  9.14  21.6
2  0.02729   0.0   7.07    0  0.469  ...  242.0     17.8  392.83  4.03  34.7
3  0.03237   0.0   2.18    0  0.458  ...  222.0     18.7  394.63  2.94  33.4
4  0.06905   0.0   2.18    0  0.458  ...  222.0     18.7  396.90  5.33  36.2

[5 rows x 14 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    category
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    category
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: category(2), float64(12)
memory usage: 49.0 KB

In [17]:
df['Price'] = boston.target
df.head()

      CRIM    ZN  INDUS CHAS    NOX  ...  PTRATIO       B  LSTAT  MEDV  Price
0  0.00632  18.0   2.31    0  0.538  ...     15.3  396.90   4.98  24.0   24.0
1  0.02731   0.0   7.07    0  0.469  ...     17.8  396.90   9.14  21.6   21.6
2  0.02729   0.0   7.07    0  0.469  ...     17.8  392.83   4.03  34.7   34.7
3  0.03237   0.0   2.18    0  0.458  ...     18.7  394.63   2.94  33.4   33.4
4  0.06905   0.0   2.18    0  0.458  ...     18.7  396.90   5.33  36.2   36.2

[5 rows x 15 columns]

## Dividing Depend and Independent into Feature

In [18]:
x = df.iloc[ :,:-1]

In [19]:
df.head()

      CRIM    ZN  INDUS CHAS    NOX  ...  PTRATIO       B  LSTAT  MEDV  Price
0  0.00632  18.0   2.31    0  0.538  ...     15.3  396.90   4.98  24.0   24.0
1  0.02731   0.0   7.07    0  0.469  ...     17.8  396.90   9.14  21.6   21.6
2  0.02729   0.0   7.07    0  0.469  ...     17.8  392.83   4.03  34.7   34.7
3  0.03237   0.0   2.18    0  0.458  ...     18.7  394.63   2.94  33.4   33.4
4  0.06905   0.0   2.18    0  0.458  ...     18.7  396.90   5.33  36.2   36.2

[5 rows x 15 columns]

In [20]:
y = df.iloc[:,-1]

In [21]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: Price, dtype: float64

## Implement Linear Regression

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

x = x.astype(float)
y = y.astype(float)

lin_reg = LinearRegression()
mse = cross_val_score(lin_reg, x, y, scoring = 'neg_mean_squared_error', cv = 5)
print(mse)
lin_reg.fit(x,y)
lin_reg.score(x,y)

[-4.13734343e-28 -7.54838350e-28 -5.92348624e-29 -7.64632722e-28
 -4.30439219e-27]

1.0

In [25]:
mean_mse = np.mean(mse)
print("MSE scores per fold: ", mse, "\n")
print("Average Negative MSE: ", mean_mse )

MSE scores per fold:  [-4.13734343e-28 -7.54838350e-28 -5.92348624e-29 -7.64632722e-28
 -4.30439219e-27]

Average Negative MSE:  -1.2593664939038093e-27

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)
lin_reg.fit(x_train, y_train)

LinearRegression()

In [27]:
prediction = lin_reg.predict(x_test)

In [28]:
print (prediction)

[22.6 50.  23.   8.3 21.2 19.9 20.6 18.7 16.1 18.6  8.8 17.2 14.9 10.5
 50.  29.  23.  33.3 29.4 21.  23.8 19.1 20.4 29.1 19.3 23.1 19.6 19.4
 38.7 18.7 14.6 20.  20.5 20.1 23.6 16.8  5.6 50.  14.5 13.3 23.9 20.
 19.8 13.8 16.5 21.6 20.3 17.  11.8 27.5 15.6 23.1 24.3 42.8 15.6 21.7
 17.1 17.2 15.  21.7 18.6 21.  33.1 31.5 20.1 29.8 15.2 15.  27.5 22.6
 20.  21.4 23.5 31.2 23.7  7.4 48.3 24.4 22.6 18.3 23.3 17.1 27.9 44.8
 50.  23.  21.4 10.2 23.3 23.2 18.9 13.4 21.9 24.8 11.9 24.3 13.8 24.7
 14.1 18.7 28.1 19.8]

##Compare Few Value VS Actual Value

In [29]:
import pandas as pd
comparison_df = pd.DataFrame({'Actual Value': y_test, 'Predicted Value': prediction})
print(comparison_df.head())

     Actual Value  Predicted Value
329          22.6             22.6
371          50.0             50.0
219          23.0             23.0
403           8.3              8.3
78           21.2             21.2

In [30]:
from sklearn import metrics
import numpy as np

#1. R-squared Score (Best Possible Score is 1.0 )
r2 = metrics.r2_score(y_test, prediction)

#2. Mean Absolute Error  (Average Error in "Price" Units)
mae = metrics.mean_absolute_error(y_test, prediction)

#3. Root Mean Squared Error (Standard Division Of Prediction Errors)
rmse = np.sqrt(metrics.mean_squared_error(y_test, prediction))

print(f"R-squared Score: {r2:.4f}")
print(f"Mean Absolute Error (MAE): {mae:.4f}" )
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")

R-squared Score: 1.0000
Mean Absolute Error (MAE): 0.0000
Root Mean Squared Error (RMSE): 0.0000